url: http://hack.british-hci2015.org/
baseurl:

# Site settings
title: British HCI 2015 HackFest
email: enquiries@british-hci2015.org
description: "British HCI 2015 HackFest webpage."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: dd0000
  secondary: a89f6c
  secondary-dark: 333

# Team names, titles and social links
people:
- name: John Shearer
  pic: shearer
  position: HackFest Chair
  social:
    - title: github
      url: https://github.com/shearer12345/
    - title: facebook
      url: https://www.facebook.com/shearer12345
    - title: twitter
      url: https://twitter.com/shearer12345_j
    - title: linkedin
      url: https://www.linkedin.com/in/shearer12345

- name: Connie Golsteijn
  pic: golsteijn
  position: HackFest Deputy Chair
  social:
    - title: twitter
      url: https://twitter.com/ConnieGolsteijn
    - title: facebook
      url: https://www.facebook.com/connie.golsteijn
    - title: linkedin
      url: https://uk.linkedin.com/in/conniegolsteijn

- name: Amy Guy
  pic: guy
  position: HackFest Deputy Chair
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/HCI_2015
  - title: github
    url: https://github.com/lincolnSocialComputing/british-hci2015-hackfest

# Postal address (add as many lines as necessary)
address:
  - line: Lincoln Social Computing Research Centre
  - line: University of Lincoln, Lincoln, LN6 7TS, UK

# Collections

collections:
  hackers:
    output: true
    permalink: /hacker/:name

# Build settings
markdown: kramdown
permalink: pretty
